# Generated by Django 5.2.8 on 2025-11-20 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0002_order_orderitem'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='sellers.seller'),
        ),
    ]
