# Generated by Django 4.2.26 on 2025-12-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banner_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Aaramba', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Upload your site logo', null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, help_text='Upload your favicon (ico or png)', null=True, upload_to='site/')),
                ('loader_image', models.ImageField(blank=True, help_text='Upload your page loader image', null=True, upload_to='site/')),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
